# Reference: <https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions>


# Workflow label
name: Build

# Workflow trigger
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Workflow tasks
jobs:
  # Build dependencies (=web resources)
  build-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # https://github.com/marketplace/actions/checkout
      with:
        repository: substation-beta/ssb_highlight_js_extension
        ref: master
        token: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
    - name: Install nodejs
      uses: actions/setup-node@v2 # https://github.com/marketplace/actions/setup-node-js-environment
    - name: Install ssb_highlight_js_extension dependencies
      run: yarn install
    - name: Build ssb_highlight_js_extension
      run: yarn run build
    - name: Upload ssb_highlight_js_extension artifact
      uses: actions/upload-artifact@v2  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: highlight-build
        path: dist
  # Build project
  build:
    needs: build-deps
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # https://github.com/marketplace/actions/checkout
    - name: Cache build
      uses: actions/cache@v2  # https://github.com/marketplace/actions/cache
      with:
        path: target
        key: cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Download dependencies
      uses: actions/download-artifact@v2  # https://github.com/marketplace/actions/download-a-build-artifact
      with:
        name: highlight-build
        path: artifacts/highlight-build
    - name: Move highlight.js to correct folder
      run: mv artifacts/highlight-build/ssb.highlight.min.js ./ssb.highlight.min.js
    - name: Build
      run: cargo build
    - name: Upload artifact
      uses: actions/upload-artifact@v2  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: ssb-book-build-ready
        path: target/book
  # Deploy build output
  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download build
        uses: actions/download-artifact@v2  # https://github.com/marketplace/actions/download-a-build-artifact
        with:
          name: ssb-book-build-ready
          path: artifacts/ssb-book-build-ready
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3 # https://github.com/marketplace/actions/github-pages-action
        with:
          personal_token: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
          publish_branch: master
          publish_dir: artifacts/ssb-book-build-ready
          external_repository: substation-beta/substation-beta.github.io
